services:
  graphdb:
    image: neo4j:5.23.0
    environment:
      NEO4J_AUTH: none
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - "neo4j-data:/data"
    ports:
      - 7474:7474
      - 7687:7687
volumes:
  neo4j-data:
