services:
  loaddb:
    image: neo4j:5.23.0
    environment:
      NEO4J_AUTH: none
    volumes:
      - "neo4j-data:/data"
      - "./source:/source"
    command: sh -c "cat /source/contact-tracing-50.dump | neo4j-admin database load neo4j --from-stdin --overwrite-destination"

  graphdb:
    image: neo4j:5.23.0
    environment:
      NEO4J_AUTH: none
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - "neo4j-data:/data"
    ports:
      - 7474:7474
      - 7687:7687
    depends_on:
      loaddb:
        condition: service_completed_successfully
volumes:
  neo4j-data:
